const LOGIN = "LOGIN";
const CREDIT_CARD = "CREDTI_CARD";
const CREDIT_CARD_PROVIDER = "CREDIT_CARD_PROVIDER";
const CREDIT_CARD_STATUS="CREDIT_CARD_STATUS"

export const MainConstants = {
  LOGIN,
  CREDIT_CARD,
  CREDIT_CARD_PROVIDER,
  CREDIT_CARD_STATUS
}


export const Constants = {
  login: {
    LOGIN_USER: `${LOGIN}-LOGIN_USER`,
    GET_LOGIN_USER: `${LOGIN}-GET_LOGGED_IN_USER`,
    AUTHENTICATE: `${LOGIN}-AUTHENTICATE`,
    LOGOUT_USER: `${LOGIN}-LOGOUT_USER`
  },
  creditCard: {
    GET_CREDIT_CARD: `${CREDIT_CARD}-GET_CREDIT_CARD`,
    ADD_CREDIT_CARD: `${CREDIT_CARD}-ADD_CREDIT_CARD`,
    RELOAD: `${CREDIT_CARD}-RELOAD`
  },
  creditCardProvider: {
    GET_CREDIT_CARD_PROVIDER: `${CREDIT_CARD_PROVIDER}-GET_CREDIT_CARD_PROVIDER`,
    ADD_CREDIT_CARD_PROVIDER: `${CREDIT_CARD_PROVIDER}-ADD_CREDIT_CARD_PROVIDER`,
    UPDATE_CREDIT_CARD_PROVIDER: `${CREDIT_CARD_PROVIDER}-UPDATE_CREDIT_CARD_PROVIDER`,
    RELOAD: `${CREDIT_CARD_PROVIDER}-RELOAD`
  },
  creditCardStatus: {
    GET_CREDIT_CARD_STATUS: `${CREDIT_CARD_STATUS}-GET_CREDIT_CARD_STATUS`,
    RELOAD: `${CREDIT_CARD_STATUS}-RELOAD`,
    FETCH_ALL_REQUEST: `${CREDIT_CARD_STATUS}-FETCH_ALL_REQUEST`,
    FETCH_ALL_SUCCESS: `${CREDIT_CARD_STATUS}-FETCH_ALL_SUCCESS`,
    FETCH_ALL_FAILURE: `${CREDIT_CARD_STATUS}-FETCH_ALL_FAILURE`,
    SET_GRID_PAGINATION: `${CREDIT_CARD_STATUS}-GRID_PAGINATION`,
    FETCH_SINGLE_REQUEST: `${CREDIT_CARD_STATUS}-FETCH_SINGLE_REQUEST`,
    FETCH_SINGLE_SUCCESS: `${CREDIT_CARD_STATUS}-FETCH_SINGLE_SUCCESS`,
    FETCH_SINGLE_FAILURE: `${CREDIT_CARD_STATUS}-FETCH_SINGLE_FAILURE`,
    POST_SINGLE_REQUEST: `${CREDIT_CARD_STATUS}-POST_SINGLE_REQUEST`,
    POST_SINGLE_SUCCESS: `${CREDIT_CARD_STATUS}-POST_SINGLE_SUCCESS`,
    POST_SINGLE_FAILURE: `${CREDIT_CARD_STATUS}-POST_SINGLE_FAILURE`,
    DELETE_SINGLE_REQUEST: `${CREDIT_CARD_STATUS}-DELETE_SINGLE_REQUEST`,
    DELETE_SINGLE_SUCCESS: `${CREDIT_CARD_STATUS}-DELETE_SINGLE_SUCCESS`,
    DELETE_SINGLE_FAILURE: `${CREDIT_CARD_STATUS}-DELETE_SINGLE_FAILURE`,
    UPDATE_SINGLE_REQUEST: `${CREDIT_CARD_STATUS}-UPDATE_SINGLE_REQUEST`,
    UPDATE_SINGLE_SUCCESS: `${CREDIT_CARD_STATUS}-UPDATE_SINGLE_SUCCESS`,
    UPDATE_SINGLE_FAILURE: `${CREDIT_CARD_STATUS}-UPDATE_SINGLE_FAILURE`
  },
  api: {
    HOST: "http://localhost:6003/api"
  }
}